version: 0.2

phases:
    build:
        commands:
        - echo Build Starting on `date`
        - mvn package

artifacts:
  files:
    - appspec.yml
    - target/demo-1.0-SNAPSHOT.jar
  discard-paths: yes
